"""phase 2 market data

Revision ID: 0002_market_data
Revises: 0001_foundation
Create Date: 2026-09-25 13:39:05.994076

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002_market_data"
down_revision: str | Sequence[str] | None = "0001_foundation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stocks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("exchange", sa.String(length=3), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("listed_on", sa.Date(), nullable=True),
        sa.Column("delisted_on", sa.Date(), nullable=True),
        sa.Column("added_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("exchange IN ('NSE','BSE')", name="ck_stocks_exchange"),
        sa.ForeignKeyConstraint(
            ["added_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "exchange", name="uq_stocks_symbol_exchange"),
    )
    op.create_table(
        "data_ingestion_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=60), nullable=False),
        sa.Column("licensed", sa.Boolean(), nullable=False),
        sa.Column("basis", sa.String(length=20), nullable=True),
        sa.Column("requested_start", sa.Date(), nullable=False),
        sa.Column("requested_end", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rows_received", sa.Integer(), nullable=False),
        sa.Column("rows_inserted", sa.Integer(), nullable=False),
        sa.Column("rows_unchanged", sa.Integer(), nullable=False),
        sa.Column("rows_revised", sa.Integer(), nullable=False),
        sa.Column("rows_rejected", sa.Integer(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("usable", sa.Boolean(), nullable=False),
        sa.Column("validation_report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("triggered_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running','succeeded','succeeded_with_warnings','rejected','failed')",
            name="ck_ingestion_status",
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ingestion_stock_started",
        "data_ingestion_runs",
        ["stock_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "corporate_actions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column("numerator", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("denominator", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("amount_basis", sa.String(length=20), nullable=True),
        sa.Column("source", sa.String(length=60), nullable=False),
        sa.Column("data_version", sa.Integer(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingestion_run_id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(kind = 'split' AND numerator > 0 AND denominator > 0 AND amount IS NULL) OR (kind = 'dividend' AND amount > 0 AND numerator IS NULL AND denominator IS NULL)",
            name="ck_corp_action_fields",
        ),
        sa.CheckConstraint(
            "amount_basis IS NULL OR amount_basis IN ('raw','split_adjusted','total_return')",
            name="ck_amount_basis",
        ),
        sa.CheckConstraint("kind IN ('split','dividend')", name="ck_corp_action_kind"),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["data_ingestion_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "stock_id", "kind", "ex_date", "source", "data_version", name="uq_corp_action_version"
        ),
    )
    op.create_table(
        "data_conflicts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("entity", sa.String(length=30), nullable=False),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("source", sa.String(length=60), nullable=False),
        sa.Column("previous_version", sa.Integer(), nullable=False),
        sa.Column("new_version", sa.Integer(), nullable=False),
        sa.Column("previous_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("new_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ingestion_run_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["data_ingestion_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_data_conflicts_stock", "data_conflicts", ["stock_id", "detected_at"], unique=False
    )
    op.create_table(
        "prices",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("interval", sa.String(length=4), nullable=False),
        sa.Column("basis", sa.String(length=20), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=60), nullable=False),
        sa.Column("licensed", sa.Boolean(), nullable=False),
        sa.Column("data_version", sa.Integer(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingestion_run_id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "basis IN ('raw','split_adjusted','total_return')", name="ck_prices_basis"
        ),
        sa.CheckConstraint("interval = '1d'", name="ck_prices_interval"),
        sa.CheckConstraint("available_at >= effective_at", name="ck_prices_availability"),
        sa.CheckConstraint(
            "low > 0 AND high >= low AND open BETWEEN low AND high AND close BETWEEN low AND high AND volume >= 0",
            name="ck_prices_ohlcv",
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["data_ingestion_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "stock_id",
            "interval",
            "basis",
            "source",
            "session_date",
            "data_version",
            name="uq_prices_version",
        ),
    )
    op.create_index(
        "ix_prices_lookup", "prices", ["stock_id", "basis", "session_date"], unique=False
    )
    # ### end Alembic commands ###

    # Market-data history is immutable: revisions are new data_version rows.
    op.execute(
        """
        CREATE FUNCTION market_data_immutable() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% is immutable (% not permitted); insert a new data_version',
                TG_TABLE_NAME, TG_OP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in ("prices", "corporate_actions", "data_conflicts"):
        op.execute(
            f"CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION market_data_immutable()"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in ("prices", "corporate_actions", "data_conflicts"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_immutable ON {table}")
    op.execute("DROP FUNCTION IF EXISTS market_data_immutable()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_prices_lookup", table_name="prices")
    op.drop_table("prices")
    op.drop_index("ix_data_conflicts_stock", table_name="data_conflicts")
    op.drop_table("data_conflicts")
    op.drop_table("corporate_actions")
    op.drop_index("ix_ingestion_stock_started", table_name="data_ingestion_runs")
    op.drop_table("data_ingestion_runs")
    op.drop_table("stocks")
    # ### end Alembic commands ###
