"""phase 3 agents and feature store

Revision ID: 0003_agents
Revises: 0002_market_data
Create Date: 2026-09-25 14:04:24.642034

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003_agents"
down_revision: str | Sequence[str] | None = "0002_market_data"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent", sa.String(length=40), nullable=False),
        sa.Column("agent_version", sa.String(length=40), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("knowledge_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("data_snapshot_id", sa.String(length=64), nullable=True),
        sa.Column("config_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("requested_by", sa.UUID(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('ok','insufficient_data','data_unusable','failed')", name="ck_agent_status"
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_runs_stock_asof", "agent_runs", ["stock_id", "agent", "as_of"], unique=False
    )
    op.create_table(
        "agent_outputs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_table(
        "technical_indicators",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("feature_name", sa.String(length=60), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=60), nullable=False),
        sa.Column("basis", sa.String(length=20), nullable=False),
        sa.Column("calculation_version", sa.String(length=40), nullable=False),
        sa.Column("availability_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("agent_run_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "stock_id",
            "feature_name",
            "session_date",
            "calculation_version",
            "data_snapshot_id",
            name="uq_feature_value",
        ),
    )
    op.create_index(
        "ix_features_lookup",
        "technical_indicators",
        ["stock_id", "feature_name", "session_date"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Agent outputs and feature values are immutable records (reuses 0002's function).
    for table in ("agent_outputs", "technical_indicators"):
        op.execute(
            f"CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION market_data_immutable()"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in ("agent_outputs", "technical_indicators"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_immutable ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_features_lookup", table_name="technical_indicators")
    op.drop_table("technical_indicators")
    op.drop_table("agent_outputs")
    op.drop_index("ix_agent_runs_stock_asof", table_name="agent_runs")
    op.drop_table("agent_runs")
    # ### end Alembic commands ###
