"""phase 4 financials

Revision ID: 0004_financials
Revises: 0003_agents
Create Date: 2026-09-25 15:58:20.509523

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004_financials"
down_revision: str | Sequence[str] | None = "0003_agents"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financials",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("period_type", sa.String(length=10), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("line_item", sa.String(length=60), nullable=False),
        sa.Column("value", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("source", sa.String(length=60), nullable=False),
        sa.Column("licensed", sa.Boolean(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("availability_estimated", sa.Boolean(), nullable=False),
        sa.Column("data_version", sa.Integer(), nullable=False),
        sa.Column("ingestion_run_id", sa.Integer(), nullable=False),
        sa.CheckConstraint("period_type IN ('annual','quarterly')", name="ck_fin_period_type"),
        sa.CheckConstraint(
            "available_at::date >= period_end", name="ck_fin_available_after_period"
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["data_ingestion_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "stock_id",
            "period_type",
            "period_end",
            "line_item",
            "source",
            "data_version",
            name="uq_financials_version",
        ),
    )
    op.create_index(
        "ix_financials_lookup",
        "financials",
        ["stock_id", "line_item", "period_type", "period_end"],
        unique=False,
    )
    # ### end Alembic commands ###
    op.execute(
        "CREATE TRIGGER financials_immutable BEFORE UPDATE OR DELETE ON financials "
        "FOR EACH ROW EXECUTE FUNCTION market_data_immutable()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS financials_immutable ON financials")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_financials_lookup", table_name="financials")
    op.drop_table("financials")
    # ### end Alembic commands ###
