"""phase 5 news documents

Revision ID: 0005_news
Revises: 0004_financials
Create Date: 2026-09-26 02:00:11.416925

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005_news"
down_revision: str | Sequence[str] | None = "0004_financials"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("doc_type", sa.String(length=30), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("pages", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("embedding_model", sa.String(length=120), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "doc_type IN ('annual_report','quarterly_report','transcript','filing','presentation','announcement','other')",
            name="ck_document_type",
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256", name="uq_documents_sha256"),
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_chunks_document", "document_chunks", ["document_id", "chunk_index"], unique=False
    )
    op.create_table(
        "news",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("title_key", sa.String(length=32), nullable=False),
        sa.Column("publisher", sa.String(length=200), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=60), nullable=False),
        sa.Column("licensed", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("historical_use", sa.Boolean(), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("mentions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sentiment_label", sa.String(length=10), nullable=True),
        sa.Column("sentiment_score", sa.Float(), nullable=True),
        sa.Column("sentiment_probs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sentiment_model", sa.String(length=120), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column("duplicate_of", sa.Integer(), nullable=True),
        sa.Column("ingestion_run_id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "sentiment_label IS NULL OR sentiment_label IN ('positive','negative','neutral')",
            name="ck_news_sentiment",
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of"],
            ["news.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["data_ingestion_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stock_id", "title_key", name="uq_news_stock_title"),
    )
    op.create_index("ix_news_stock_published", "news", ["stock_id", "published_at"], unique=False)
    # ### end Alembic commands ###
    op.execute(
        "CREATE INDEX ix_chunks_embedding ON document_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE TRIGGER news_immutable BEFORE DELETE ON news "
        "FOR EACH ROW EXECUTE FUNCTION market_data_immutable()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS news_immutable ON news")
    op.execute("DROP INDEX IF EXISTS ix_chunks_embedding")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_news_stock_published", table_name="news")
    op.drop_table("news")
    op.drop_index("ix_chunks_document", table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_table("documents")
    # ### end Alembic commands ###
