"""phase 6 macro

Revision ID: 0006_macro
Revises: 0005_news
Create Date: 2026-09-26 02:12:39.871153

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006_macro"
down_revision: str | Sequence[str] | None = "0005_news"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "macro_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("series", sa.String(length=60), nullable=False),
        sa.Column("frequency", sa.String(length=10), nullable=False),
        sa.Column("period_date", sa.Date(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=30), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("licensed", sa.Boolean(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("availability_estimated", sa.Boolean(), nullable=False),
        sa.Column("data_version", sa.Integer(), nullable=False),
        sa.Column("entered_by", sa.UUID(), nullable=True),
        sa.CheckConstraint("frequency IN ('daily','annual','event')", name="ck_macro_frequency"),
        sa.ForeignKeyConstraint(
            ["entered_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "series", "period_date", "source", "data_version", name="uq_macro_version"
        ),
    )
    op.create_index("ix_macro_series_date", "macro_data", ["series", "period_date"], unique=False)
    # ### end Alembic commands ###
    op.execute(
        "CREATE TRIGGER macro_data_immutable BEFORE UPDATE OR DELETE ON macro_data "
        "FOR EACH ROW EXECUTE FUNCTION market_data_immutable()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS macro_data_immutable ON macro_data")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_macro_series_date", table_name="macro_data")
    op.drop_table("macro_data")
    # ### end Alembic commands ###
