"""phase 8 reports

Revision ID: 0008_reports
Revises: 0007_portfolio
Create Date: 2026-09-26 02:32:53.002656

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008_reports"
down_revision: str | Sequence[str] | None = "0007_portfolio"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("knowledge_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("requested_by", sa.UUID(), nullable=True),
        sa.Column("stance", sa.String(length=30), nullable=False),
        sa.Column("composite_score", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("agent_run_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("report_hash", sa.String(length=64), nullable=False),
        sa.Column("config_fingerprint", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_reports_stock_created", "analysis_reports", ["stock_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###
    op.execute(
        "CREATE TRIGGER analysis_reports_immutable BEFORE UPDATE OR DELETE ON analysis_reports "
        "FOR EACH ROW EXECUTE FUNCTION market_data_immutable()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS analysis_reports_immutable ON analysis_reports")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reports_stock_created", table_name="analysis_reports")
    op.drop_table("analysis_reports")
    # ### end Alembic commands ###
