"""phase 9 trading

Revision ID: 0009_trading
Revises: 0008_reports
Create Date: 2026-09-26 02:43:31.501042

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0009_trading"
down_revision: str | Sequence[str] | None = "0008_reports"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("equity", sa.Float(), nullable=False),
        sa.Column("cash", sa.Float(), nullable=False),
        sa.Column("invested", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_snapshots_portfolio_taken",
        "portfolio_snapshots",
        ["portfolio_id", "taken_at"],
        unique=False,
    )
    op.create_table(
        "trade_proposals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=True),
        sa.Column("ticker", sa.String(length=30), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("mode", sa.String(length=5), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("stop_loss", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("target", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("mode IN ('paper','live')", name="ck_proposal_mode"),
        sa.CheckConstraint("side IN ('buy','sell')", name="ck_proposal_side"),
        sa.CheckConstraint("quantity > 0", name="ck_proposal_qty"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_proposals_portfolio_created",
        "trade_proposals",
        ["portfolio_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "trade_decisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("proposal_id", sa.Integer(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decision", sa.String(length=10), nullable=False),
        sa.Column("first_failure", sa.String(length=40), nullable=True),
        sa.Column("failed_gates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("costs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("engine_version", sa.String(length=40), nullable=False),
        sa.Column("config_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("decision_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint("decision IN ('APPROVED','REJECTED')", name="ck_decision_value"),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["trade_proposals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("proposal_id"),
    )
    # ### end Alembic commands ###
    op.execute(
        "CREATE TRIGGER trade_proposals_immutable BEFORE UPDATE OR DELETE ON trade_proposals "
        "FOR EACH ROW EXECUTE FUNCTION market_data_immutable()"
    )
    op.execute(
        "CREATE TRIGGER trade_decisions_immutable BEFORE UPDATE OR DELETE ON trade_decisions "
        "FOR EACH ROW EXECUTE FUNCTION market_data_immutable()"
    )
    op.execute(
        "CREATE TRIGGER portfolio_snapshots_immutable BEFORE UPDATE OR DELETE ON portfolio_snapshots "
        "FOR EACH ROW EXECUTE FUNCTION market_data_immutable()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trade_proposals_immutable ON trade_proposals")
    op.execute("DROP TRIGGER IF EXISTS trade_decisions_immutable ON trade_decisions")
    op.execute("DROP TRIGGER IF EXISTS portfolio_snapshots_immutable ON portfolio_snapshots")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trade_decisions")
    op.drop_index("ix_proposals_portfolio_created", table_name="trade_proposals")
    op.drop_table("trade_proposals")
    op.drop_index("ix_snapshots_portfolio_taken", table_name="portfolio_snapshots")
    op.drop_table("portfolio_snapshots")
    # ### end Alembic commands ###
