"""phase 11 paper

Revision ID: 0011_paper
Revises: 0010_backtests
Create Date: 2026-09-26 03:10:30.634947

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0011_paper"
down_revision: str | Sequence[str] | None = "0010_backtests"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=False),
        sa.Column("decision_id", sa.Integer(), nullable=False),
        sa.Column("recheck_decision_id", sa.Integer(), nullable=True),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=30), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.CheckConstraint("side IN ('buy','sell')", name="ck_paper_order_side"),
        sa.CheckConstraint("status IN ('FILLED','REJECTED')", name="ck_paper_order_status"),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["trade_decisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recheck_decision_id"],
            ["trade_decisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_paper_order_idem"),
    )
    op.create_index(
        "ix_paper_orders_portfolio", "paper_orders", ["portfolio_id", "created_at"], unique=False
    )
    op.create_table(
        "paper_executions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("reference_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("fill_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("notional", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("fees", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("fee_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("realised_pnl", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("cash_after", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("fill_model", sa.String(length=60), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["paper_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    op.create_table(
        "theses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=30), nullable=False),
        sa.Column("entry_order_id", sa.Integer(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("stop_loss", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("target", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("horizon_end", sa.Date(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=True),
        sa.Column("invalidation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('OPEN','CLOSED')", name="ck_thesis_status"),
        sa.ForeignKeyConstraint(
            ["entry_order_id"],
            ["paper_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["analysis_reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_theses_portfolio_status", "theses", ["portfolio_id", "status"], unique=False
    )
    op.create_table(
        "thesis_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("thesis_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("session", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("exit_proposal_id", sa.Integer(), nullable=True),
        sa.Column("exit_decision", sa.String(length=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["exit_proposal_id"],
            ["trade_proposals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thesis_id"],
            ["theses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("thesis_id", "kind", "session", name="uq_thesis_event_once"),
    )
    # ### end Alembic commands ###
    op.execute(
        "CREATE TRIGGER paper_executions_immutable BEFORE UPDATE OR DELETE ON paper_executions "
        "FOR EACH ROW EXECUTE FUNCTION market_data_immutable()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS paper_executions_immutable ON paper_executions")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("thesis_events")
    op.drop_index("ix_theses_portfolio_status", table_name="theses")
    op.drop_table("theses")
    op.drop_table("paper_executions")
    op.drop_index("ix_paper_orders_portfolio", table_name="paper_orders")
    op.drop_table("paper_orders")
    # ### end Alembic commands ###
