"""phase 12 ranking

Revision ID: 0012_ranking
Revises: 0011_paper
Create Date: 2026-09-26 09:32:10.965076

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0012_ranking"
down_revision: str | Sequence[str] | None = "0011_paper"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("link", sa.String(length=200), nullable=True),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("deliveries", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("severity IN ('info','warning','critical')", name="ck_alert_severity"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key", name="uq_alert_dedupe"),
    )
    op.create_index("ix_alerts_created", "alerts", ["created_at"], unique=False)
    op.create_table(
        "ranking_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=True),
        sa.Column("headline", sa.String(length=80), nullable=False),
        sa.Column("qualified", sa.Integer(), nullable=False),
        sa.Column("evaluated", sa.Integer(), nullable=False),
        sa.Column("rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gate_failure_counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("operational_blockers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("config_fingerprint", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_ranking_runs_as_of", "ranking_runs", ["as_of"], unique=False)
    # ### end Alembic commands ###
    # A ranking is a record of what the system said at the time; counterfactual
    # analysis compares it with what happened later, so it must never change.
    op.execute(
        "CREATE TRIGGER ranking_runs_immutable BEFORE UPDATE OR DELETE ON ranking_runs "
        "FOR EACH ROW EXECUTE FUNCTION market_data_immutable()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS ranking_runs_immutable ON ranking_runs")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ranking_runs_as_of", table_name="ranking_runs")
    op.drop_table("ranking_runs")
    op.drop_index("ix_alerts_created", table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
