"""phase 13 monitoring

Revision ID: 0013_monitoring
Revises: 0012_ranking
Create Date: 2026-09-26 09:42:07.565087

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0013_monitoring"
down_revision: str | Sequence[str] | None = "0012_ranking"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_monitor_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("drift", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("calibration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("predictions_logged", sa.Integer(), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("action", sa.String(length=10), nullable=False),
        sa.Column("config_fingerprint", sa.String(length=64), nullable=False),
        sa.CheckConstraint("action IN ('none','retired')", name="ck_monitor_action"),
        sa.CheckConstraint("status IN ('PASS','WARN','FAIL','UNKNOWN')", name="ck_monitor_status"),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_model_monitor_runs_model_asof",
        "model_monitor_runs",
        ["model_id", "as_of"],
        unique=False,
    )
    op.create_table(
        "model_predictions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("session", sa.Date(), nullable=False),
        sa.Column("predicted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon", sa.Integer(), nullable=False),
        sa.Column("p_profit", sa.Float(), nullable=False),
        sa.Column("p_outperform", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_id", "stock_id", "session", name="uq_model_prediction"),
    )
    op.create_index(
        "ix_model_predictions_model_session",
        "model_predictions",
        ["model_id", "session"],
        unique=False,
    )
    op.add_column(
        "model_versions",
        sa.Column("feature_reference", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###
    # Logged predictions and monitoring results are evidence: never edited.
    for table in ("model_predictions", "model_monitor_runs"):
        op.execute(
            f"CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION market_data_immutable()"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in ("model_predictions", "model_monitor_runs"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_immutable ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_versions", "feature_reference")
    op.drop_index("ix_model_predictions_model_session", table_name="model_predictions")
    op.drop_table("model_predictions")
    op.drop_index("ix_model_monitor_runs_model_asof", table_name="model_monitor_runs")
    op.drop_table("model_monitor_runs")
    # ### end Alembic commands ###
